export default {
    syncUpdate: {
        appUpdate: 'アプリ更新',
        continue: '次へ',
        install: 'インストール',
        ignore: 'スキップ',
        upToDate: '最新バージョン',
        updateTitle: '利用可能なアップデート',
        mandatoryUpdateMessage: 'アップデートをインストールするには確認が必要です：',
        optionalUpdateMessage: 'アップデート利用可能：',
        downloadingPackage: 'パッケージのダウンロード。。。',
        installingUpdate: 'インストールされている。。。',
        updateInstalled: 'インストールされました！',
    },
    common: {
        defaultLanguage: 'English',
        close: '閉じる',
        noText: 'テキストなし',
        noData: 'データなし',
        cancel: 'キャンセル',
        confirm: '決定',
        save: '保存',
        sendOTP: {
            title: '認証コード',
            titleForgotPassword: 'パスワードを忘れた',
            sendForgotPassword: '確認',
            backButton: '前の画面',
            descriptionNext:
                '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「次へ」ボタンを押してください。有効期限は24時間です。',
            descriptionConfirm:
                '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「確認」ボタンを押してください。有効期限は24時間です。',
            description:
                '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「登録」ボタンを押してください。有効期限は24時間です。',
            resend: '再送信',
            buttonSend: '登録',
            buttonNext: '次へ',
        },
        picker: {
            pickItem: 'アイテムを選択してください',
        },
        error: {
            unknown: '不明なエラーが発生しました。',
            network: 'エラーが発生しました。暫くしてから、もう一度試してください。',
        },
        yes: 'はい',
        email: 'メールアドレス',
        name: '名前',
        birthday: '生年月日',
        gender: '性別',
        changePass: 'パスワード変更',
    },

    // screens
    tab: {
        home: 'ホーム',
        stamp: 'スタンプ',
        order: '注文',
        coupon: 'クーポン',
        setting: 'マイページ',
        account: 'アカウント',
        notification: '通知',
    },
    authen: {
        login: {
            placeholderEmail: 'メールアドレス',
            placeholderPassword: 'パスワード',
            buttonLogin: 'ログイン',
            rememberText: 'ログイン状態を保持',
            forgotPasswordText: 'パスワードを忘れた方はこちら',
            registerText: '新規会員登録はこちら',
        },
        register: {
            title: '新規会員登録はこちら',
            emailPlaceholder: 'sample@demo.webcom',
            namePlaceholder: 'name',
            birthdayPlaceholder: 'birthday',
            password: 'パスワード',
            passwordPlaceholder: 'パスワード',
            passwordConfirm: 'パスワード（再入力）',
            backButton: '前の画面',
            photo: '画像',
            camera: 'カメラ',
            cancel: 'キャンセル',
        },
        sendEmail: {
            title: 'パスワードを忘れた',
            sendButtonTitle: '次へ',
        },
    },
    home: {},
    account: {},
    notification: {},
    order: {
        menuTitle: 'メニュー',
        changeCart: 'カートの変更',
        couponTitle: 'クーポンリスト',
        useCoupon: 'クーポン使用',
        applyCoupon: 'クーポンを適用',
        keep: '保存',
        orderGuide: '注文ガイド',
    },
    setting: {
        editProfileTitle: 'マイページ編集',
        editProfile: '保存',
        cancel: 'キャンセル',
        orderHistoryTitle: '注文履歴',
        orderHistoryDetailTitle: '注文詳細',
        timeOrder: '注文日時',
        orderDefaultTitle: 'いつもの！注文',
        viewCart: 'カートを見る',
        orderSaveTitle: 'いつもの！注文',
        position: 'タイトル',
        content: '内容',
        contactTitle: '問い合わせ',
        send: '送信',
        settingNotificationTitle: '通知設定',
        pushNotification: 'プッシュ通知',
        emailNotification: 'メール通知',
    },

    // alert
    alert: {
        success: '新規コードを送りました。',
        invalidOTP: '認証コードは正しくありません。',
    },

    // error
    error: {
        signIn: '入力されたイメルまたはパスワードが正しくありません。',
        infoInvalid: '情報は正しくありません。',
        notCompleted: '全ての項目に入力してください。',
        validatePassword: 'パスワードは半角英数字で6文字以上入力する必要があります。',
        passwordLength: 'パスワードは8文字以上で入力してください。',
        confirmPasswordLength: '確認パスワードは文字以上を入力してください。',
        passwordNotMatch: '入力された新パスワードが一致しません。ご確認ください。',
        duplicatePassword: 'パスワードは二重されました。',
        emailExisted: 'メールアドレスが既に存在します。',
        emailInvalid: 'メールアドレスの形式が間違っています。',
        emailEmpty: '全ての項目を入力してください。',
        emailNotRegister: '入力したメールアドレスがまだ登録されていません。',
        phoneInvalid: '電話番号は正しくありません。',
        nameLength: '5文字から8文字までに入力してください。',
        trimSpace: '文頭や文末には空白文字を入力しないでください。',
        messageLength: '1文字以上 255文字以内。',
        require: '{{field}}は記入必須の項目です。',
        maxLength: '8文字以内で入力してください。',
        minLength: '8文字以上で入力してください。',
        inputComponent:
            'You need to wrap input by Form Provider or passing "form = useForm( ... )" into input component.',
    },
    stamp: {
        title: 'スタンプカード',
        noteUse: '押していないスタンプがｎ個あります。\n押す場合はこの欄をタッチ！',
        canUse: '使用可',
        used: '有効期限切れ',
        rangeDate: '{{start}}－{{end}}',
        titleCount: '獲得数',
        count: '{{count}} 個',
        exchangeStamp: '交換\nカード',
        cumulativeStamp: '累計\nカード',
        guideTitle: 'スタンプカードの詳細',
    },
    chooseStamp: {
        earnStamp: 'スタンプが貯まる',
        orderId: '注文ID: ADDS',
        pleaseChoose: '貯まるスタンプを選択してください',
    },
    stampDetail: {
        title: '新年スタンプカード',
        expired: '有効期限切れ',
        numberOfRemain: '残数',
        numberOfCollect: '獲得数',
        numberOfUse: '使用数',
        count: '{{count}} 個',
        historyExchange: 'クーポン交換履歴',
        couponExchangeBtn: 'クーポン交換',
        couponGetHistory: 'クーポンGET履歴',
        modalGetCoupon: 'クーポンGET',
    },
    exchangeCoupon: {
        title: 'クーポン交換',
        listCanExchange: 'クーポン交換できるリスト',
        btnExchange: 'クーポン交換',
        confirm: {
            title: '確認',
            content: 'このクーポンを交換すると、交換可能スタンプ残数が「ｎ個」になります。交換しますか？',
            textButtonCancel: 'いいえ',
        },
        success: {
            title: '交換完了',
            content: 'ご希望のクーポンと交換しました。',
            textButtonCancel: 'スタンプカード\nに戻る',
            textButtonOk: '獲得した\nクーポンを見る',
        },
        error: {
            title: '注意',
            content: '交換可能スタンプ残数が足りません。',
        },
    },
};
