/* App config for images
 */
const Images = {
    icons: {
        selected: require('./icon/ic_select.png'),
        back: require('./icon/ic_back.png'),
        facebook: require('./icon/ic_facebook.png'),
        line: require('./icon/ic_line.png'),
        instagram: require('./icon/ic_instagram.png'),
        tab: {
            home: require('./icon/ic_home.png'),
            notification: require('./icon/ic_notification.png'),
            setting: require('./icon/ic_setting.png'),
            account: require('./icon/ic_account.png'),
            user: require('./icon/ic_user.png'),
            coupon: require('./icon/ic_coupon.png'),
            bag: require('./icon/ic_bag.png'),
            stamp_card: require('./icon/ic_stamp_card.png'),
        },
        radio: {
            check: require('./icon/ic_check_radio.png'),
            uncheck: require('./icon/ic_uncheck_radio.png'),
        },
        camera: require('./icon/ic_camera.png'),
        close: require('./icon/ic_close.png'),
        closeCircle: require('./icon/ic_close_circle.png'),
        eyeOff: require('./icon/ic_eye_off.png'),
        eyeOn: require('./icon/ic_eye_on.png'),
        message: require('./icon/ic_message.png'),
        stampUsed: require('./icon/ic_stamp_used.png'),
        couponUsed: require('./icon/ic_coupon_used.png'),
        question: require('./icon/ic_question.png'),
        noodlesOn: require('./icon/ic_noodles_on.png'),
        noodlesOff: require('./icon/ic_noodles_off.png'),
        ticket_discount: require('./icon/ic_ticket_discount.png'),
        promotion: require('./icon/ic_promotion.png'),
        stamp_card: require('./icon/ic_stamp_card.png'),
        shop: require('./icon/ic_shop.png'),
        coupon: require('./icon/ic_coupon.png'),
        couponBlue: require('./icon/ic_coupon_blue.png'),
        document: require('./icon/ic_document.png'),
        arrow_left: require('./icon/ic_arrow_left.png'),
        arrowLeftPrimary: require('./icon/ic_arrow_left_primary.png'),
        bag: require('./icon/ic_bag.png'),
        cancel: require('./icon/ic_cancel.png'),
        add: require('./icon/ic_add.png'),
        minus: require('./icon/ic_minus.png'),
        next: require('./icon/ic_next.png'),
        nextGrey: require('./icon/ic_next_grey.png'),
        arrowNext: require('./icon/ic_arrow_next.png'),
        calendar: require('./icon/ic_calendar.png'),
        gold: require('./icon/ic_gold.png'),
        edit: require('./icon/ic_edit.png'),
        contact: require('./icon/ic_contact.png'),
        setting: require('./icon/ic_setting.png'),
        cart: require('./icon/ic_cart.png'),
        document_text: require('./icon/ic_document_text.png'),
        history: require('./icon/ic_history.png'),
        logout: require('./icon/ic_logout.png'),
        email: require('./icon/ic_email.png'),
        userName: require('./icon/ic_user_name.png'),
        birthday: require('./icon/ic_birthday.png'),
        gender: require('./icon/ic_gender.png'),
        order: require('./icon/ic_order.png'),
        bag_happy: require('./icon/ic_bag_happy.png'),
        rectangle: require('./icon/ic_rectangle.png'),
        rectangleDisable: require('./icon/ic_rectangle_disable.png'),
        tick: require('./icon/ic_tick.png'),
        giftOpenSmall: require('./icon/gift_open_small.png'),
        giftOpen3: require('./icon/gift_open_3.png'),
        giftOpen5: require('./icon/gift_open_5.png'),
        giftOpen7: require('./icon/gift_open_7.png'),
        giftClose: require('./icon/gift_close.png'),
        confirm: require('./icon/ic_confirm.png'),
        success: require('./icon/ic_success.png'),
        error: require('./icon/ic_error.png'),
        noCoupon: require('./icon/ic_no_coupon.png'),
        step1: require('./icon/ic_step_1.png'),
        step2: require('./icon/ic_step_2.png'),
        step3: require('./icon/ic_step_3.png'),
        nextSecondary: require('./icon/next_secondary.png'),
        tickSquare: require('./icon/ic_tick_square.png'),
        untickSquare: require('./icon/ic_untick_square.png'),
    },
    photo: {
        defaultImage: require('./photo/img_default_image.png'),
        avatarDefault: require('./photo/avatar_default.png'),
        logo: require('./photo/pt_logo.png'),
        news: require('./photo/pt_news.png'),
        qrCode: require('./photo/pt_qr_code.png'),
        ptCouponDetail: require('./photo/pt_coupon_detail.png'),
        backgroundMyPage: require('./photo/pt_background_my_page.png'),
        used: require('./photo/pt_used.png'),
        line: require('./photo/pt_line.png'),
        ptLogin: require('./photo/pt_login.png'),
    },
    lottie: {
        loadingNoodleJp: require('./lotties/loadingNoodleJp.json'),
        loadingRamen: require('./lotties/loadingRamen.json'),
    },
};

export default Images;
