const AUTHENTICATE_ROUTE = {
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
    REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
    FORGOT_PASS: '@AUTHENTICATE_ROUTE/FORGOT_PASS',
    SEND_OTP: '@AUTHENTICATE_ROUTE/SEND_OTP',
    CHANGE_PASS: '@AUTHENTICATE_ROUTE/CHANGE_PASS',
    ORDER_DEFAULT_MENU: '@AUTHENTICATE_ROUTE/ORDER_DEFAULT_MENU',
    REGISTER_STEP_2: '@AUTHENTICATE_ROUTE/REGISTER_STEP_2',
    REGISTER_STEP_3: '@AUTHENTICATE_ROUTE/REGISTER_STEP_3',
    INFORMATION: '@AUTHENTICATE_ROUTE/INFORMATION',
    SEND_OTP_FORGOT_PASS: '@AUTHENTICATE_ROUTE/SEND_OTP_FORGOT_PASS',
    RESET_PASSWORD: 'RESET_PASSWORD',
};

const APP_ROUTE = {
    MAIN_TAB: 'MAIN_TAB',
};

const HOME_ROUTE = {
    ROOT: 'HOME_ROOT',
    HOME: 'HOME',
    CHECK_IN: 'CHECK_IN',
    NOTIFICATION: 'NOTIFICATION',
    NOTIFICATION_DETAIL: 'NOTIFICATION_DETAIL',
    NEW_LIST: 'NEW_LIST',
    NEW_DETAIL: 'NEW_DETAIL',
    ORDER_DEFAULT_HOME: 'ORDER_DEFAULT_HOME',
    MOBILE_ORDER: 'MOBILE_ORDER',
    CART: 'CART',
    EDIT_ORDER: 'EDIT_ORDER',
};

const SETTING_ROUTE = {
    ROOT: 'SETTING_ROOT',
    MY_PAGE: 'MY_PAGE',
    EDIT_PROFILE: 'EDIT_PROFILE',
    ORDER_HISTORY: 'ORDER_HISTORY',
    ORDER_DEFAULT_SETTING: 'ORDER_DEFAULT_SETTING',
    SETTING_NOTIFICATION: 'SETTING_NOTIFICATION',
    CONTACT: 'CONTACT',
    ORDER_HISTORY_DETAIL: 'ORDER_HISTORY_DETAIL',
    DEFAULT_ORDER_DETAIL: 'DEFAULT_ORDER_DETAIL',
    ORDER_SAVE: 'ORDER_SAVE',
};

const NOTIFICATION_ROUTE = {
    ROOT: 'NOTIFICATION_ROOT',
};

const ACCOUNT_ROUTE = {
    ROOT: 'ACCOUNT_ROUTE',
};
const ORDER_ROUTE = {
    ROOT: 'ORDER_ROUTE',
    DETAIL_MEAL: 'DETAIL_MEAL',
    CART: 'CART',
    COUPON_LIST: 'COUPON_LIST',
    DETAIL_SHOP: 'DETAIL_SHOP',
    ORDER_QR_CODE: 'ORDER_QR_CODE',
    COUPON_DETAIL: 'COUPON_DETAIL',
    CART_EDIT_QR: 'CART_EDIT_QR',
    MENU_EDIT_QR: 'MENU_EDIT_QR',
};
const STAMP_ROUTE = {
    ROOT: 'STAMP_ROUTE',
    STAMP_CARD_DETAIL: 'STAMP_CARD_DETAIL',
    EXCHANGE_COUPON: 'EXCHANGE_COUPON',
};
const COUPON_ROUTE = {
    ROOT: 'COUPON_ROUTE',
    DETAIL_COUPON: 'DETAIL_COUPON',
};
const TAB_NAVIGATION_ROOT = {
    HOME_ROUTE,
    ORDER_ROUTE,
    SETTING_ROUTE,
    NOTIFICATION_ROUTE,
    ACCOUNT_ROUTE,
    STAMP_ROUTE,
    COUPON_ROUTE,
};

export {
    APP_ROUTE,
    TAB_NAVIGATION_ROOT,
    AUTHENTICATE_ROUTE,
    HOME_ROUTE,
    ORDER_ROUTE,
    SETTING_ROUTE,
    NOTIFICATION_ROUTE,
    ACCOUNT_ROUTE,
    STAMP_ROUTE,
    COUPON_ROUTE,
};
